#!/usr/bin/env python3
"""Scan a Hermes-like repo for likely user-facing language strings.

This script is intentionally conservative. It finds candidates for the agent
to review and patch; it does not rewrite files by itself.
"""

from __future__ import annotations

import argparse
import ast
import fnmatch
import json
import os
import re
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable


DEFAULT_EXTENSIONS = {".py", ".ts", ".tsx", ".js", ".jsx", ".json", ".yaml", ".yml"}
IGNORE_DIRS = {
    ".git",
    ".hg",
    ".svn",
    ".venv",
    "venv",
    "node_modules",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    "dist",
    "build",
    "coverage",
    "web_dist",
}
GENERATED_MARKERS = {
    "generated",
    "do not edit",
    "auto-generated",
    "autogenerated",
}

CALL_NAMES = {
    "print",
    "input",
    "_cprint",
    "cprint",
    "console.print",
    "Prompt.ask",
    "Confirm.ask",
    "showToast",
    "toast",
    "add_parser",
    "add_argument",
}

HERMES_RUNTIME_SKIP_PREFIXES = (
    ".github/workflows/",
    ".github/actions/",
    "website/",
    "docs/",
    "examples/",
)
HERMES_SKIP_GLOBS = (
    "*.snap",
    "*.min.js",
    "*.bundle.js",
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock",
)

ENGLISH_RE = re.compile(r"[A-Za-z][A-Za-z0-9][A-Za-z0-9 _.,:;!?()'\"/+-]{2,}")
CJK_RE = re.compile(r"[\u3400-\u9fff]")
URL_RE = re.compile(r"https?://|wss?://|file://")
PATH_RE = re.compile(r"(^|[\\s\"'])((~?/|[A-Za-z]:\\\\|/)[^\\s\"']+)")
ENV_RE = re.compile(r"\b[A-Z][A-Z0-9_]{2,}\b")
PLACEHOLDER_RE = re.compile(r"(\{[^{}]+\}|%\([^)]+\)s|%s|\$\{[^}]+\}|\$[A-Za-z_][A-Za-z0-9_]*)")
COMMAND_RE = re.compile(r"(^|\s)(hermes|npm|python|pip|git|uv|systemctl|journalctl|launchctl|sudo|npx|node)\s+")
IDENTIFIER_HEAVY_RE = re.compile(r"^[A-Za-z0-9_./:-]+$")


@dataclass
class Candidate:
    path: str
    line: int
    surface: str
    kind: str
    label: str
    text: str
    classification: str
    reason: str


def has_english(text: str) -> bool:
    return bool(ENGLISH_RE.search(text)) and not CJK_RE.search(text)


def is_generated(path: Path, text_head: str) -> bool:
    lower_parts = {p.lower() for p in path.parts}
    if lower_parts & {"web_dist", "dist", "build", "coverage"}:
        return True
    lower_head = text_head.lower()
    return any(marker in lower_head for marker in GENERATED_MARKERS)


def classify(text: str, path: Path, generated: bool) -> tuple[str, str]:
    stripped = text.strip()
    if generated:
        return "skip-generated", "generated or build output"
    if not stripped or not has_english(stripped):
        return "skip-identifier", "no untranslated English prose"
    if path.name.upper() == "SKILL.md":
        return "skip-model-facing", "skill instruction body"
    if path.suffix.lower() == ".json" and len(stripped) < 24:
        return "skip-identifier", "short JSON value"
    if "prompt" in path.name.lower() and len(stripped) > 80:
        return "review", "possible model-facing prompt"
    if IDENTIFIER_HEAVY_RE.fullmatch(stripped):
        return "skip-identifier", "identifier-like text"
    protected = []
    if URL_RE.search(stripped):
        protected.append("url")
    if PATH_RE.search(stripped):
        protected.append("path")
    if ENV_RE.search(stripped):
        protected.append("env")
    if PLACEHOLDER_RE.search(stripped):
        protected.append("placeholder")
    if COMMAND_RE.search(stripped):
        protected.append("command")
    if protected:
        return "mixed-preserve", "contains " + ", ".join(protected)
    if len(stripped.split()) <= 2 and re.search(r"[_./:-]", stripped):
        return "skip-identifier", "short technical token"
    return "translate", "likely user-facing prose"


def should_skip_rel(rel: str, profile: str, include_ci: bool, include_docs: bool) -> bool:
    rel_lower = rel.lower()
    if profile == "hermes":
        for prefix in HERMES_RUNTIME_SKIP_PREFIXES:
            if rel_lower.startswith(prefix):
                if prefix.startswith(".github/") and include_ci:
                    continue
                if prefix in {"docs/", "website/", "examples/"} and include_docs:
                    continue
                return True
        return any(fnmatch.fnmatch(Path(rel_lower).name, pattern) for pattern in HERMES_SKIP_GLOBS)
    return False


def surface_for(rel: str) -> str:
    if rel.startswith("ui-tui/"):
        return "tui"
    if rel.startswith("web/"):
        return "web"
    if rel.startswith("gateway/"):
        return "gateway"
    if rel.startswith("tools/"):
        return "tools"
    if rel.startswith("hermes_cli/") or rel == "cli.py" or rel == "run_agent.py":
        return "cli"
    if rel.startswith("agent/"):
        return "agent"
    if rel.startswith("plugins/"):
        return "plugin"
    if rel.startswith("locales/"):
        return "locale"
    if rel.startswith(".github/"):
        return "ci"
    if rel.startswith("docs/") or rel.startswith("website/"):
        return "docs"
    return "other"


def iter_files(
    root: Path,
    include_tests: bool,
    profile: str,
    include_ci: bool,
    include_docs: bool,
) -> Iterable[Path]:
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [
            d for d in dirnames
            if d.lower() not in IGNORE_DIRS
            and (include_tests or d.lower() not in {"tests", "__tests__"})
        ]
        base = Path(dirpath)
        for filename in filenames:
            path = base / filename
            rel = path.relative_to(root).as_posix()
            if should_skip_rel(rel, profile, include_ci, include_docs):
                continue
            if path.suffix.lower() not in DEFAULT_EXTENSIONS and path.name.upper() != "SKILL.md":
                continue
            yield path


def call_name(node: ast.AST) -> str:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        parent = call_name(node.value)
        return f"{parent}.{node.attr}" if parent else node.attr
    return ""


def py_string_value(node: ast.AST) -> str | None:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    if isinstance(node, ast.JoinedStr):
        parts: list[str] = []
        for value in node.values:
            if isinstance(value, ast.Constant) and isinstance(value.value, str):
                parts.append(value.value)
            elif isinstance(value, ast.FormattedValue):
                parts.append("{expr}")
        return "".join(parts)
    return None


def scan_python(path: Path, rel: str, text: str, generated: bool) -> list[Candidate]:
    candidates: list[Candidate] = []
    surface = surface_for(rel)
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return scan_regex(path, rel, text, generated)
    for node in ast.walk(tree):
        if isinstance(node, ast.Call):
            name = call_name(node.func)
            interesting = name in CALL_NAMES or name.endswith(".print") or name.endswith(".ask")
            if not interesting:
                continue
            for arg in list(node.args) + [kw.value for kw in node.keywords if kw.arg in {"help", "description", "title"}]:
                value = py_string_value(arg)
                if value is None:
                    continue
                cls, reason = classify(value, path, generated)
                if cls.startswith("skip") and cls != "skip-generated":
                    continue
                candidates.append(Candidate(rel, getattr(node, "lineno", 1), surface, "python-call", name, value, cls, reason))
    return candidates


JS_QUOTED_RE = re.compile(
    r"(?P<label>showToast|console\.print|aria-label|title|placeholder|alt|label|description|help|DialogTitle|Tooltip|SelectOption|Button)"
    r"[^\\n]{0,80}?(?P<quote>['\"`])(?P<text>(?:\\.|(?!\2).)*?)(?P=quote)"
)
JS_TEXT_RE = re.compile(r">(?P<text>[^<>{}\n]*[A-Za-z][^<>{}\n]{2,})<")
YAML_VALUE_RE = re.compile(
    r"^\s*(?P<label>description|title|help|label|name|summary|placeholder):\s*(?P<quote>['\"]?)(?P<text>.*?)(?P=quote)\s*$"
)
JSON_VALUE_RE = re.compile(
    r"\"(?P<label>description|title|help|label|name|summary|placeholder)\"\s*:\s*\"(?P<text>(?:\\.|[^\"])*)\""
)


def scan_regex(path: Path, rel: str, text: str, generated: bool) -> list[Candidate]:
    candidates: list[Candidate] = []
    surface = surface_for(rel)
    suffix = path.suffix.lower()
    for lineno, line in enumerate(text.splitlines(), 1):
        if suffix in {".ts", ".tsx", ".js", ".jsx"}:
            for match in JS_QUOTED_RE.finditer(line):
                value = match.group("text").strip()
                cls, reason = classify(value, path, generated)
                if cls.startswith("skip") and cls != "skip-generated":
                    continue
                candidates.append(Candidate(rel, lineno, surface, "quoted", match.group("label"), value, cls, reason))
        if suffix in {".tsx", ".jsx"}:
            for match in JS_TEXT_RE.finditer(line):
                value = match.group("text").strip()
                cls, reason = classify(value, path, generated)
                if cls.startswith("skip") and cls != "skip-generated":
                    continue
                candidates.append(Candidate(rel, lineno, surface, "jsx-text", "text-node", value, cls, reason))
        if suffix in {".yaml", ".yml"}:
            match = YAML_VALUE_RE.search(line)
            if match:
                value = match.group("text").strip().strip("'\"")
                cls, reason = classify(value, path, generated)
                if cls.startswith("skip") and cls != "skip-generated":
                    continue
                candidates.append(Candidate(rel, lineno, surface, "yaml-value", match.group("label"), value, cls, reason))
        if suffix == ".json":
            for match in JSON_VALUE_RE.finditer(line):
                value = match.group("text").strip()
                cls, reason = classify(value, path, generated)
                if cls.startswith("skip") and cls != "skip-generated":
                    continue
                candidates.append(Candidate(rel, lineno, surface, "json-value", match.group("label"), value, cls, reason))
    return candidates


def scan_file(root: Path, path: Path) -> list[Candidate]:
    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return []
    rel = path.relative_to(root).as_posix()
    generated = is_generated(path, text[:1000])
    if path.suffix == ".py":
        return scan_python(path, rel, text, generated)
    return scan_regex(path, rel, text, generated)


def write_markdown(candidates: list[Candidate]) -> str:
    lines = [
        "# Localization Candidates",
        "",
        "| File | Line | Class | Label | Text | Reason |",
        "|---|---:|---|---|---|---|",
    ]
    for c in candidates:
        text = c.text.replace("|", "\\|").replace("\n", "\\n")
        if len(text) > 180:
            text = text[:177] + "..."
        lines.append(f"| `{c.path}` | {c.line} | `{c.classification}` | `{c.surface}:{c.label}` | {text} | {c.reason} |")
    lines.append("")
    counts: dict[str, int] = {}
    surfaces: dict[str, int] = {}
    for c in candidates:
        counts[c.classification] = counts.get(c.classification, 0) + 1
        surfaces[c.surface] = surfaces.get(c.surface, 0) + 1
    if counts:
        lines.append("## Counts by Classification")
        lines.append("")
        for key, value in sorted(counts.items()):
            lines.append(f"- `{key}`: {value}")
        lines.append("")
    if surfaces:
        lines.append("## Counts by Surface")
        lines.append("")
        for key, value in sorted(surfaces.items()):
            lines.append(f"- `{key}`: {value}")
        lines.append("")
    lines.append(f"Total candidates: {len(candidates)}")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Scan likely user-facing strings in a Hermes-like repo.")
    parser.add_argument("root", type=Path, help="Repository root")
    parser.add_argument("--format", choices=("json", "markdown"), default="json")
    parser.add_argument("--out", type=Path, help="Output file. Defaults to stdout.")
    parser.add_argument("--profile", choices=("hermes", "generic"), default="hermes", help="Project profile. Hermes skips CI/docs/site by default.")
    parser.add_argument("--include-tests", action="store_true", help="Include tests and __tests__ directories")
    parser.add_argument("--include-ci", action="store_true", help="Include .github workflows/actions")
    parser.add_argument("--include-docs", action="store_true", help="Include docs, website, and examples")
    parser.add_argument("--classes", nargs="*", help="Only include these classifications")
    parser.add_argument("--surfaces", nargs="*", help="Only include these surfaces, e.g. cli web tui gateway")
    args = parser.parse_args()

    root = args.root.resolve()
    candidates: list[Candidate] = []
    for path in iter_files(
        root,
        include_tests=args.include_tests,
        profile=args.profile,
        include_ci=args.include_ci,
        include_docs=args.include_docs,
    ):
        candidates.extend(scan_file(root, path))

    if args.classes:
        wanted = set(args.classes)
        candidates = [c for c in candidates if c.classification in wanted]
    if args.surfaces:
        wanted_surfaces = set(args.surfaces)
        candidates = [c for c in candidates if c.surface in wanted_surfaces]

    candidates.sort(key=lambda c: (c.path, c.line, c.text))
    if args.format == "json":
        output = json.dumps([asdict(c) for c in candidates], ensure_ascii=False, indent=2)
    else:
        output = write_markdown(candidates)

    if args.out:
        args.out.write_text(output + "\n", encoding="utf-8")
    else:
        print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
